# Generated by Django 5.1 on 2024-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.IntegerField()),
                ('request_number', models.IntegerField()),
                ('reporting_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=255)),
                ('equipment_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('fault_reported', models.TextField()),
                ('diagnosis', models.TextField()),
                ('action_done', models.TextField()),
                ('required_spare_parts', models.TextField()),
            ],
        ),
    ]
