# Generated by Django 5.1 on 2024-08-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-reporting_date', 'job_number'], 'verbose_name': 'Job Card', 'verbose_name_plural': 'Job Cards'},
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='action_done',
            field=models.TextField(verbose_name='Action Done'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='department',
            field=models.CharField(max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='equipment_name',
            field=models.CharField(max_length=255, verbose_name='Equipment Name'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='fault_reported',
            field=models.TextField(verbose_name='Fault Reported'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Job Number'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='reported_by',
            field=models.CharField(max_length=255, verbose_name='Reported By'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='reporting_date',
            field=models.DateField(verbose_name='Reporting Date'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='request_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Request Number'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='required_spare_parts',
            field=models.TextField(verbose_name='Required Spare Parts'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='ward',
            field=models.CharField(max_length=255, verbose_name='Ward'),
        ),
    ]
